/**
 * `probe`, verification of a capability's declared outcomes, on demand.
 *
 * Probing runs automatically at the end of `discover`, but it is deliberately
 * available on its own, for two reasons that both matter more than convenience:
 *
 *  - **A reviewer can add what the model could not.** The commonest reason an
 *    outcome goes unprobed is that nothing in the recording said which input
 *    would provoke it. A human who knows the application can write that probe
 *    into the artifact and verify it here, without paying for a rediscovery and
 *    without the capability changing underneath them.
 *
 *  - **It needs no model, so anyone can reproduce it.** Discovery is the one
 *    path in this system that costs money and cannot be replayed. Probing is
 *    ordinary deterministic replay wearing a different hat, so the evidence
 *    behind an `observed` outcome can be regenerated by a reviewer with a
 *    checkout and no API key at all.
 */

import { PlaywrightWebSurface } from '../surface/playwright-web.js';
import { PolicyEngine, PROBE_POLICY } from '../policy/engine.js';
import { Redactor } from '../policy/redaction.js';
import { RunLogger, newRunId } from '../evidence/logger.js';
import { loadArtifact, saveArtifact } from '../artifact/store.js';
import {
  probeOutcomes,
  baselineInputsFor,
  withProbingProvenance,
  renderProbeSummary,
} from '../discovery/probe.js';
import { DEFAULT_TENANT, TENANT_RUNTIMES, headless, resolveCredentials } from '../config.js';

export interface ProbeCommandOptions {
  capability: string;
  version?: number;
  tenant: string;
  headless?: boolean;
  maxProbes?: number;
  /** Baseline inputs, for capabilities whose recorded example is missing. */
  inputs?: Record<string, string>;
  /** Report what probing found without writing it back to the artifact. */
  dryRun?: boolean;
  /** Re-verify only outcomes whose evidence has aged out or is missing. */
  staleOnly?: boolean;
}

export async function runProbeCommand(opts: ProbeCommandOptions): Promise<number> {
  const tenant = TENANT_RUNTIMES[opts.tenant] ?? TENANT_RUNTIMES[DEFAULT_TENANT]!;
  const artifact = loadArtifact(opts.capability, opts.version);

  if (artifact.outcomes.length === 0) {
    process.stdout.write(`\n${artifact.id} declares no business outcomes. Nothing to probe.\n\n`);
    return 0;
  }

  const runId = newRunId('probe');
  const credentials = resolveCredentials(tenant.id);
  const redactor = new Redactor();
  redactor.addLiteral(credentials.operatorPassword);

  const logger = new RunLogger({ runId, redactor });
  logger.event('run_started', `probe ${artifact.id} v${artifact.version}`, {
    capability: artifact.id,
    outcomes: artifact.outcomes.map((o) => o.code),
  });

  const policy = new PolicyEngine({ ...PROBE_POLICY, allowedOrigins: [new URL(tenant.baseUrl).origin] });

  // One surface per probe run, opened and closed by the prober. A probe is a
  // claim about what a replay will do, and a replay starts from a cold browser.
  const newDriver = () =>
    PlaywrightWebSurface.launch({
      policy,
      redactor,
      headless: headless(opts.headless),
      onEvent: (type, message, data) => {
        if (type === 'policy_decision' && message.includes('allow')) return;
        logger.event(type as never, message, data);
      },
    });

  {
    const probed = await probeOutcomes({
      artifact,
      newDriver,
      baselineInputs: baselineInputsFor(artifact, credentials, opts.inputs ?? {}),
      bindings: { baseUrl: tenant.baseUrl },
      policy,
      logger,
      ...(opts.maxProbes ? { maxProbes: opts.maxProbes } : {}),
      ...(opts.staleOnly ? { staleOnly: true } : {}),
    });

    const updated = withProbingProvenance(probed);

    // A pass that learned nothing writes nothing. Probing an irreversible
    // capability, or one whose outcomes carry no probe declarations, produces
    // no observation to record, and rewriting the artifact anyway would
    // reserialise a reviewed, possibly hand-authored file for no reason. The
    // first run of this command did exactly that to `open_sub_account`, whose
    // outcomes it had just correctly declined to probe: a read-only operation
    // that modified its input.
    const path = opts.dryRun
      ? '(dry run, not written)'
      : probed.learnedSomething
        ? saveArtifact(updated)
        : '(unchanged: nothing was probed)';
    logger.writeJson('probed-artifact.json', updated, { redact: false });
    logger.event('run_finished', `probe finished: ${summaryLine(probed.reports)}`);

    process.stdout.write(
      `\n${'─'.repeat(72)}\n` +
        `  Probed capability: ${updated.id} v${updated.version}\n` +
        `${'─'.repeat(72)}\n\n` +
        renderProbeSummary(probed) +
        probed.warnings.map((w) => `  ! ${w}\n\n`).join('') +
        `  artifact     ${path}\n` +
        `  evidence     ${logger.dir}\n` +
        `${'─'.repeat(72)}\n` +
        `${summaryLine(probed.reports)}\n\n`,
    );

    // A refuted outcome is a finding, not a crash, so it is reported through
    // the exit code the same way replay reports a business outcome: 2 means
    // "ran fine, and the answer is not the one you wanted".
    return probed.reports.some((r) => r.state === 'refuted') ? 2 : 0;
  }
}

function summaryLine(reports: Array<{ state: string }>): string {
  const count = (state: string) => reports.filter((r) => r.state === state).length;
  return `${count('observed')} observed · ${count('refuted')} refuted · ${count('skipped')} not probed`;
}
